global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
scrape_configs:

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'proposta'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app-proposta:8080']
  
  - job_name: 'proposta-docker'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['app-proposta:8081']

  - job_name: 'contas'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'contas:8888' ]

  - job_name: 'analise'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'analise:9999' ]

  - job_name: 'transacoes'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'transacoes:7777' ]
       